import "@/app/styles/globals.css";
import Navbar from "@/components/navbars/admin/navbar";
import "../../../public/fonts/IRANYekanX/fontiran.css";

export const metadata = {
  title: "Contractor Documents",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Navbar />
        <main className="container mx-auto">{children}</main>
      </body>
    </html>
  );
}
