import "@/app/styles/globals.css";
import Navbar from "@/components/navbars/admin/navbar";

export const metadata = {
  title: "Contractor Documents",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}