import "@/app/styles/globals.css";
import Navbar from "@/components/Navbar/AnonymousNavbar";

export const metadata = {
  title: "Contractor Documents",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="min-h-screen">
        <Navbar />
        <main className="flex flex-col items-center justify-between">
          {children}
        </main>
      </body>
    </html>
  );
}
